default_agent: ep_agent
agents:
  ep_agent:
    name: ep_agent
    entrypoint: ep_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::561605471310:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-2d4fe0aa6c
      execution_role_auto_create: false
      account: '561605471310'
      region: us-east-1
      ecr_repository: 561605471310.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-ep_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: ep_agent-qR5A9m2TT9
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:561605471310:runtime/ep_agent-qR5A9m2TT9
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-ep_agent-builder
      execution_role: arn:aws:iam::561605471310:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-2d4fe0aa6c
      source_bucket: bedrock-agentcore-codebuild-sources-561605471310-us-east-1
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_9YpMeBgjH/.well-known/openid-configuration
        allowedClients:
        - 70fgkn9bg38jb4e84p9l0htfa4
    oauth_configuration: null
